import type { Metadata } from "next";
import PermanentDrawerLeft from "./_components/PermanentDrawerLeft";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <PermanentDrawerLeft>{children}</PermanentDrawerLeft>
    </>
  );
}
